---
title: "Presentations"
subtitle: "My presentations. Open access."
---

___
### **2019**

1. Stanciu, A. (2019). Horizontal transmission of elderly stereotypes from native population to immigrants: A multi-theory exploration across 29 countries. Presentation at the 4th ESS Conference, Mannheim, Germany. [slides](https://osf.io/vu6pa/)

2. Witte, EH., **Stanciu, A.**, & Boehnke, K. (2019). The Distribution Approach and The Averaging Approach: A Tale of Two Methodologies Meant to Measure Value Preferences at the Culture Level. Presentation at the 4th ESS Conference, Mannheim, Germany. [slides](https://osf.io/evhrf/)

___
### **2018**

1. Stanciu, A. (2018). A new empirical approach to inter-cultural comparisons of value preferences based on Schwartz’s theory. Presentation at the ICS SPARC Group Seminar, Lisbon, Portugal. [slides](https://osf.io/5w2vj/)

2. Stanciu, A., Witte, EH., & Boehnke, K. (2018). A new empirical approach to inter-cultural comparisons of value preferences based on Schwartz’s theory. Presentation at the 51st Congress of the German Psychological Society (DGPs), Frankfurt am Main, Germany. [slides](https://osf.io/x9jgp/)

3. Stanciu, A., Smallenbroek, O., Arant, R., & Boehnke, K. (2018). Value development trajectories and political engagement in mid-adulthood: Evidence from a three-decade longitudinal study of peace movement sympathizers and activists. Presentation at the Conflict Research Society (CRS) Annual Conference, Birmingham, UK. [slides](https://osf.io/yehav/)

4. Stanciu, A., Witte, EH., & Boehnke, K. (2018). Introducing the ‘distribution approach’ as an alternative methodology to empirically arrive at value priorities at the culture level. Presentation at the IACCP International Congress, Guelph, Canada. [slides](https://osf.io/32zw8/)

5. Stanciu, A. (2018). On how a combination of the Social Network Paradigm and focus group interviews can provide insights into ‘cultural fluidity’. Poster presentation at the IACCP International Congress, Guelph, Canada. [poster](https://osf.io/fr24x/)

___
### **2017**

1. Stanciu, A. (2017). Overall and Contextually-Bound Well-Being: A Suggestion of Life Satisfaction as Different Facets of Well-Being. Presentation at the IACCP Regional Congress, Warsaw, Poland. [slides](https://osf.io/9r7nx/)

1. Stanciu, A. (2017). Under-Represented Ethnic and Cultural Groups from the Eastern European Context. A Research Incubator for Young Academics, IACCP Regional Congress, Warsaw, Poland. (*Organized symposium*). [slides](https://osf.io/b359m/)

___
### **2016**

1. Stanciu, A., Vauclair, CM., Koc, Y., Miconi, D., Farcas, D., Kisliogly, R., & Rodda, N. (2016). Four Dimensions of Stereotypes: Evidence from Romania and a Seven-Culture Test of Structure Reliability. Presentation at the IACCP International Congress, Nagoya, Japan. [slides](https://osf.io/yvdez/)

2. Stanciu, A. (2016). Stereotype Based Faultlines: The effects of a Stereotypically-Consistent Composition of Groups on Inter-Group Relations. Presentation at the ICP Congress, Yokohama, Japan. [slides](https://osf.io/8pwhg/)

3. Stanciu, A. (2016). Adaptation of Personal Stereotypes to Cultural Stereotypes: Research Suggestions and Initial Evidence. Presentation at Diaspora Conference on Research and Graduate Education in Romania, Timisoara, Romania. [slides](https://osf.io/m6f8j/)

4. Irem, U., Alper, S., Kemmelmeier, M.,...**Stanciu, A.**...Quero, B. (2016). The Position But Not the Omission of Pronouns Influences Self-Construal. Presentation at the 17th Annual Conventiaon of Society for Personality and Social Psychology, Sand Diego, USA.

___
### **2015**

1. Stanciu, A. (2015). When Stereotypes Acculturate. Cognitive Adaptation Patterns of Romanian Migrants in Four European Countries. Presentation at the IAIR international Congress, Bergen, Norway. [slides](https://osf.io/x8mks/)

___
### **2014**

1. Stanciu, A. (2014). Have You Heard of the Maneliști? An Incursion Into the Cultural Stereotypes of Romanians. Presentation at the IACCP International Congress, Reims, France. [slides](https://osf.io/fzbg9/)

2. Stanciu, A. (2014). Introducing the Integrative Model of Stereotype Acculturation (tIMoSA): A Complementary Psychological and Sociological Perspective About the Stereotypes Held by Migrants. Presentation at the IACCP International Congress, Reims, France. [slides](https://osf.io/msbdg/)

3. Stanciu, A. (2014). The Roles of Culture and Migration in Shaping and Re-shaping the Content of Stereotypes. Presentation at the 28th EFPSA Congress, Baile Felix, Romania. [slides](https://osf.io/mt43g/)

4. Stanciu, A. (2014). From Pieces To the Whole Using Structural Equation Modelling: The Case of Scale Construction for Measuring Stereotype Content In the Romanian Cultural Context. Presentation at SocLife Spring Workshop on Statistics, Cologne, Germany. [slides](https://osf.io/baj2d/)

5. Stanciu, A. (2014). The Integrative Model of Stereotype Acculturation. A joint Psychological and Sociological Perspective About the Changes in Stereotypes Held by Migrants. Presentation at MIGREMUS Colloquium on International and Spatial Mobility, Bremen, Germany. [slides](https://osf.io/z93ew/)

___
### **2013**

1. Stanciu, A. (2013). When Stereotypes Acculturate: The Integrative Model of Stereotype Acculturation. Presentation at SoDoc-2013 PhD Workshop, Cologne, Germany. [slides](https://osf.io/rmcjv/)

